import type { Metadata } from "next";
import "./globals.css";
import { IframeProvider } from "@/components/IframeProvider";
import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
  title: "Teable App",
  description: "Generated by Teable",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <IframeProvider>{children}</IframeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
