import type { Metadata } from "next";
import "./globals.css";
import { IframeProvider } from "@/components/IframeProvider";

export const metadata: Metadata = {
  title: "Teable App",
  description: "Generated by Teable",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <IframeProvider>{children}</IframeProvider>
      </body>
    </html>
  );
}
